from cs_student import db
from cs_student.models import Student, Course, Logs, Attendance
import datetime 
d = datetime.date(2020, 2, 17)
student_1 = Student(name='Nguyet Do', course_id=1)
student_2 = Student(name='An Dang', course_id=1)
student_3 = Student(name='Kieu Tuan Anh', course_id=1)
student_4 = Student(name='Tobias Becher', course_id=1)
student_5 = Student(name='Pham Tuan Anh', course_id=1)
student_6 = Student(name='Phuc Tran', course_id=1)
student_7 = Student(name='Tin Ngo', course_id=1)
student_8 = Student(name='Luu Quang Thang', course_id=1)
student_9 = Student(name='Tran Duy Minh', course_id=1)
student_10 = Student(name='Kha Nguyen', course_id=1)
student_11 = Student(name='An Vu', course_id=1)
student_12 = Student(name='Dung Ho', course_id=1)
student_13 = Student(name='Nguyet Vo', course_id=1)
student_14 = Student(name='Chau Tran', course_id=1)
student_15 = Student(name='Nguyen Khoa Nguyen', course_id=1)
student_16 = Student(name='Tran Khoe', course_id=1)
student_17 = Student(name='Tran Tran', course_id=1)


log_1 = Logs(student_id= 1, activities='init_student', point=100, date=d)
log_2 = Logs(student_id= 2, activities='init_student', point=100, date=d)
log_3 = Logs(student_id= 3, activities='init_student', point=100, date=d)
log_4 = Logs(student_id= 4, activities='init_student', point=100, date=d)
log_5 = Logs(student_id= 5, activities='init_student', point=100, date=d)
log_6 = Logs(student_id= 6, activities='init_student', point=100, date=d)
log_7 = Logs(student_id= 7, activities='init_student', point=100, date=d)
log_8 = Logs(student_id= 8, activities='init_student', point=100, date=d)
log_9 = Logs(student_id= 9, activities='init_student', point=100, date=d)
log_10 = Logs(student_id= 10, activities='init_student', point=100, date=d)
log_11 = Logs(student_id= 11, activities='init_student', point=100, date=d)
log_12 = Logs(student_id= 12, activities='init_student', point=100, date=d)
log_13 = Logs(student_id= 13, activities='init_student', point=100, date=d)
log_14 = Logs(student_id= 14, activities='init_student', point=100, date=d)
log_15 = Logs(student_id= 15, activities='init_student', point=100, date=d)
log_16 = Logs(student_id= 16, activities='init_student', point=100, date=d)
log_17 = Logs(student_id= 17, activities='init_student', point=100, date=d)


attedance_1 = Attendance(student_id= 1, date=d)
attedance_4 = Attendance(student_id= 4, date=d) 
attedance_3 = Attendance(student_id= 3, date=d) 
attedance_5 = Attendance(student_id= 5, date=d) 
attedance_6 = Attendance(student_id= 6, date=d) 
attedance_7 = Attendance(student_id= 7, date=d) 
attedance_2 = Attendance(student_id= 2, date=d) 
attedance_8 = Attendance(student_id= 8, date=d) 
attedance_9 = Attendance(student_id= 9, date=d) 
attedance_10 = Attendance(student_id= 10, date=d)
attedance_11 = Attendance(student_id= 11, date=d)
attedance_12 = Attendance(student_id= 12, date=d)
attedance_13 = Attendance(student_id= 13, date=d)
attedance_14 = Attendance(student_id= 14, date=d)
attedance_15 = Attendance(student_id= 15, date=d)
attedance_16 = Attendance(student_id= 16, date=d)
attedance_17 = Attendance(student_id= 17, date=d)

course_1 = Course(course_name='Full-Time-MLE', cohort='Tonga')
course_2 = Course(course_name='Full-Time-MLE', cohort='Mariana')
course_3 = Course(course_name='Full-Time-MLE', cohort='Fansipan')

db.session.add(course_1)
db.session.add(course_2)
db.session.add(course_3)
db.session.commit()

db.session.add(student_1)
db.session.add(student_2)
db.session.add(student_3)
db.session.add(student_4)
db.session.add(student_5)
db.session.add(student_6)
db.session.add(student_7)
db.session.add(student_8)
db.session.add(student_9)
db.session.add(student_10)
db.session.add(student_11)
db.session.add(student_12)
db.session.add(student_13)
db.session.add(student_14)
db.session.add(student_15)
db.session.add(student_16)
db.session.add(student_17)
db.session.commit()

db.session.add(log_1)
db.session.add(log_2)
db.session.add(log_3)
db.session.add(log_4)
db.session.add(log_5)
db.session.add(log_6)
db.session.add(log_7)
db.session.add(log_8)
db.session.add(log_9)
db.session.add(log_10)
db.session.add(log_11)
db.session.add(log_12)
db.session.add(log_13)
db.session.add(log_14)
db.session.add(log_15)
db.session.add(log_16)
db.session.add(log_17)
db.session.commit()

db.session.add(attedance_3 )
db.session.add(attedance_4 )
db.session.add(attedance_1 )
db.session.add(attedance_5 )
db.session.add(attedance_6 )
db.session.add(attedance_7 )
db.session.add(attedance_2 )
db.session.add(attedance_8 )
db.session.add(attedance_9 )
db.session.add(attedance_10)
db.session.add(attedance_11)
db.session.add(attedance_12)
db.session.add(attedance_13)
db.session.add(attedance_14)
db.session.add(attedance_15)
db.session.add(attedance_16)
db.session.add(attedance_17)
db.session.commit()
